CREATE TABLE IF NOT EXISTS LESSON_OCCURRENCE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lesson_id INTEGER NOT NULL,
    date DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (lesson_id) REFERENCES LESSON(id)
);
